name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go binary for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

      - name: Zip the binary
        run: zip function.zip bootstrap

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-zip
          path: function.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your AWS region

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-golang-service \
            --zip-file fileb://function.zip \
            --publish
